name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (if present)
        run: npm run build --if-present

      # - name: Run tests
        # run: npm test

  deploy:
    # only deploy once, and only when pushing to main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      # choose a single node version for any possible predeploy steps
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # install just in case you need any build artifacts to exist locally
      - name: Install dependencies
        run: npm ci

      # If you need to rebuild for deploy (optional); remove if already built in build job and artifacts are used.
      - name: Build for deployment
        run: npm run build --if-present

      # ========= FTP deploy step =========
      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || '21' }}
          # local-dir: ${{ secrets.DEPLOY_DIR || 'out' }}
          # server-dir: ${{ secrets.FTP_REMOTE_PATH || '/public_html/' }}
          server-dir: /public_html/
          protocol: ftps
          security: strict



